<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class StoreTeacher extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array|string>
     */
    public function rules(): array
    {
        return [

            "email" => ["required", "email", "unique:teachers,email,$this->teacher"],
            "password" => ['required', 'string', 'min:5'],
            "name_ar" => ['required', 'regex:/^[\p{Arabic} ]+/u'],
            "name_en" => 'required|regex:/^[a-zA-Z ]+/',
            "specialization_id" => "required",
            "gender_id" => "required",
            "address" => ['required', 'string']
        ];
    }


    public function messages()
    {
        return []; // TODO: Change the autogenerated stub
    }


    public  function  attributes()
    {
        return [
            "email" => trans('Teacher_trans.email'),
            "password" => trans('Teacher_trans.password'),
            "name_ar" => trans('Teacher_trans.name_teacher_ar'),
            "name_en" => trans('Teacher_trans.name_teacher_en'),
            "specialization_id" => trans('Teacher_trans.specialization'),
            "gender_id" => trans('Teacher_trans.gender'),
            "address" => trans('Teacher_trans.address'),

        ]; // TODO: Change the autogenerated stub
    }
}
